### ISSUE TITLE
docker containers in state 'restarting' should be skipped

### ISSUE THREAD

**Issue by markwell-ch** [elacheche/docker_check#12]
When a container is in status `Restarting` an exception occurs, the check should only get the stats from containers that are in status `Up`.

```
docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                          PORTS                              NAMES
b0a81591a56f        dpage/pgadmin4:latest             "/entrypoint.sh"         55 minutes ago      Restarting (3) 42 seconds ago                                      pgadmin
```

```
./docker_check.py
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./docker_check.py", line 100, in get_ct_metrics
    mem_pct = get_mem_pct(stats)
  File "./docker_check.py", line 43, in get_mem_pct
    limit = stats['memory_stats']['limit']
KeyError: 'limit'
```

**Comment by elacheche** [comment]
Solved by your PR #15 

Thanks for contributing
